### ISSUE TITLE
升级到2.1.1后报错，报错信息如图片所示

### ISSUE THREAD

**Issue by Kimmyzhao** [osiegmar/logback-gelf#38]
![QQ20191104-162902](https://user-images.githubusercontent.com/11455494/68107577-439e6080-ff20-11e9-808e-f9f971c50e0c.png)
项目采用的 spring-cloud，when service-A call service-b，throw an exception
`java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;`
how to fix this problem

**Comment by osiegmar** [comment]
Unfortunately I didn't had a chance to learn Chinese, yet.  Could you please update the ticket to english?

**Comment by osiegmar** [comment]
Thanks for bringing this up! The problem appeared, because version 2.1.1 was build with Java 11 (with target for 7, of course). And Java 9 introduced overridden methods with covariant return types for some methods in `java.nio.ByteBuffer`. So, 2.1.1 would only run with Java >= 9. I fixed this issue by rebuilding with Java 8 and released 2.1.2.
