### ISSUE TITLE
Allow encoder subclasses to customize the message before it is converted to String

### ISSUE THREAD

**Issue by nemecec** [osiegmar/logback-gelf#39]
I want to add a SHA-256 fingerprint as additional field to each GELF log message. In order to achieve that with least amount of code, I would like to extend `GelfEncoder` and add that field before the message is converted to String.

I'll submit a pull request with the proposed change.

**Comment by osiegmar** [comment]
I've got your point but I doubt that the PR is enough for that. The class `GelfMessage` is still package-private and thus not designed for extending it in a proper way. The getter `getAdditionalFields()` would break encapsulation because of the mutable map (and potentially the raw `Object`). Maybe I'd extend the class design a bit further. But first, could you please write a test case to ensure that the desired functionality is provided (no need to calculate a SHA checksum of course).

**Comment by nemecec** [comment]
Thank you for your feedback. I will come back to this a bit later (another task took priority for now).
