### ISSUE TITLE
[question] tcpappender with down graylog uses 5 seconds on log 

### ISSUE THREAD

**Issue by idar** [osiegmar/logback-gelf#9]
I am seeing delays on log.info by about 5 seconds when our graylog server is down. Config below.

Is this the way its supposed to be? Udp appender would probably be much better.

`<included>

    <appender name="gelf" class="de.siegmar.logbackgelf.GelfTcpAppender">
        <graylogHost>jenkins.usrv.ubergenkom.no</graylogHost>
        <graylogPort>12201</graylogPort>
        <connectTimeout>15000</connectTimeout>
        <reconnectInterval>300</reconnectInterval>
        <maxRetries>2</maxRetries>
        <retryDelay>3000</retryDelay>
        <layout class="de.siegmar.logbackgelf.GelfLayout">
            <originHost>${HOSTNAME}</originHost>
            <includeRawMessage>false</includeRawMessage>
            <includeMarker>true</includeMarker>
            <includeMdcData>true</includeMdcData>
            <includeCallerData>true</includeCallerData>
            <includeRootCauseData>false</includeRootCauseData>
            <includeLevelName>true</includeLevelName>
            <shortPatternLayout class="ch.qos.logback.classic.PatternLayout">
                <pattern>%m%nopex</pattern>
            </shortPatternLayout>
            <fullPatternLayout class="ch.qos.logback.classic.PatternLayout">
                <pattern>%m</pattern>
            </fullPatternLayout>
            <staticField>app:${CONTEXT_NAME}</staticField>
            <staticField>constretto:${CONSTRETTO_TAGS}</staticField>
        </layout>
    </appender>

    <appender name="ASYNCGELF" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="gelf"/>
    </appender>

    <root level="INFO">
        <appender-ref ref="ASYNCGELF"/>
    </root>
</included>`

**Comment by osiegmar** [comment]
Using UDP would mean fire and forget. All messages are lost if your graylog server is down or if there's any network problem between your server and the graylog server. And you can't use TLS/SSL via UDP. Usually I use UDP if I'm on the same (trusted) network and messages can be lost without any (bigger) problems.

About your delay issue - see https://logback.qos.ch/manual/appenders.html#AsyncAppender:

Property **neverBlock**:
If false (the default) the appender will block on appending to a full queue rather than losing the message. Set to true and the appender will just drop the message and will not block your application.

This property is available since Logback 1.1.5.

Are you sure, that log.info has a delay? As per documentation of the property discardingThreshold, only WARN and ERROR should result in blocking delay - everything else is discarded if less than 20% of the queue is free.

Also note, that the default queueSize is 256 which might be to small to circumvent graylog downtimes on non-lazy systems.

**Comment by idar** [comment]
It was an error log statement. I will add true to never block that will probably fix it. This was the graylog server for our test environment that didn't come back up after a restart.
